#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://47.115.49.87:3306/shiro?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver